In [59]:
%load_ext autoreload
%reload_ext autoreload
%autoreload 2


The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [60]:
from preprocessing import generate_dataset, create_batch_2


In [61]:
data, encoder = generate_dataset()
#x, y, raw_x = create_batch_2(data.iloc[0:1])
#print(len(x), len(y))
#print(x[0].shape)
#print(raw_x[0].shape)
print(data)
# display(data[['File path', 'Raga']].to_string())

Skipping raga: Adana malhar, not enough data
Skipping raga: Ambika, not enough data
Skipping raga: Amrit varshini, not enough data
Skipping raga: Anand malhar, not enough data
Skipping raga: Arabhi, not enough data
Skipping raga: Asa mand, not enough data
Skipping raga: Ashta raga malika, not enough data
Skipping raga: Bahaduri todi, not enough data
                                             File path    Raga  \
0    ./raga-data/Abhogi/Ajoy Chakrabarty - Raag Abh...  Abhogi   
1    ./raga-data/Abhogi/Anol Chatterjee - Raag Abho...  Abhogi   
2    ./raga-data/Abhogi/Bhimsen Joshi - Rag Abhogi ...  Abhogi   
3    ./raga-data/Abhogi/Bhimsen Joshi - Rag Abhogi ...  Abhogi   
4    ./raga-data/Abhogi/Bhimsen Joshi - Rag Abhogi ...  Abhogi   
..                                                 ...     ...   
222  ./raga-data/Yaman/Veena Sahasrabuddhe - Deo da...   Yaman   
223  ./raga-data/Yaman/Veena Sahasrabuddhe - Peeyar...   Yaman   
224  ./raga-data/Yaman/Veena Sahasrabuddhe - Tana d...

In [62]:
x, y = create_batch_2(data.iloc[0:6], use_chroma = True)

________________________________________________________________________________
[Memory] Calling preprocessing.create_batch_2...
create_batch_2(                                           File path    Raga  \
0  ./raga-data/Abhogi/Ajoy Chakrabarty - Raag Abh...  Abhogi   
1  ./raga-data/Abhogi/Anol Chatterjee - Raag Abho...  Abhogi   
2  ./raga-data/Abhogi/Bhimsen Joshi - Rag Abhogi ...  Abhogi   
3  ./raga-data/Abhogi/Bhimsen Joshi - Rag Abhogi ...  Abhogi   
4  ./raga-data/Abhogi/Bhimsen Joshi - Rag Abhogi ...  Abhogi   
5  ./raga-data/Abhogi/Bhimsen Joshi - Raga Abhogi...  Abhogi   

                                        Raga One-Hot  
0  [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
1  [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
2  [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
3  [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
4  [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
5  [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  , use_chroma=True)
Ela

In [16]:
# print(x['mels'][0])
# print(x['chromas'][0])
print(y[0])
print(len(x['mels']), len(x['chromas']), len(y))
print(x['chromas'][0].shape, x['chromas'][2].shape)
print(x['chromas'][0][0].shape)
print(x['chromas'][1][0].shape)



[1. 0.]


TypeError: list indices must be integers or slices, not str

In [14]:
import librosa
import matplotlib.pyplot as plt


In [18]:
fig, ax = plt.subplots(nrows=2, sharex=True)
img = librosa.display.specshow(x['chromas'][0][0], y_axis='chroma', x_axis='time', ax=ax[0])
fig.colorbar(img, ax=[ax[0]])

img = librosa.display.specshow(x['chromas'][1][0], y_axis='chroma', x_axis='time', ax=ax[1])
fig.colorbar(img, ax=[ax[1]])
plt.show()


In [21]:
for index, audiofile in data.iterrows():
    filename = audiofile['File path']
    file_length = round(librosa.get_duration(filename = audiofile['File path']), 0)

    sr = librosa.get_samplerate(filename)
    print(sr)

44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100
44100


EOFError: 

In [6]:
x_2, y_2 = create_batch_2(data.iloc[0:6], use_chroma = False)

In [7]:
for i in range(6):
    print(x_2[i].shape)

print(x_2[348].shape)
print(len(x_2))

(128, 1023)
(128, 1023)
(128, 1023)
(128, 1023)
(128, 1023)
(128, 1023)
(128, 1023)
439


In [12]:
print(encoder.inverse_transform(y_2[341].reshape(1, -1)))
print(encoder.inverse_transform(y_2[200].reshape(1, -1)))
print(encoder.inverse_transform(y_2[0].reshape(1, -1)))
print(encoder.inverse_transform(y_2[100].reshape(1, -1)))

print(y_2[100].reshape(1, -1))
print(type(y_2[100]))
y_2[341].reshape(1, -1)


[['Bageshree']]
[['Bageshree']]
[['Bageshree']]
[['Bageshree']]
[[1. 0.]]
<class 'numpy.ndarray'>


array([[1., 0.]])

In [20]:
import numpy as np
sample = np.round(np.array([0.1, 0.5, 0.3, 0.1]), decimals = 2)
sample2 = np.round(np.random.rand(23), decimals = 2)

indices = (-sample2).argsort()[:len(sample2)]
print(sample2)
print(indices)
# print((-sample2).argsort()[:len(sample2)])

def output_2_rankings(logits, encoder, num_display = 5):
    indices = (-logits).argsort()[:len(logits)]
    for i, index in enumerate(indices):
        one_hot = np.zeros(23)
        one_hot[index] = 1
        print(one_hot)
        print(encoder.inverse_transform(one_hot.reshape(1, -1))[0][0], logits[index])

        if i == 5:
            break

output_2_rankings(sample2, encoder, num_display = 5)

[0.39 0.07 0.59 0.88 0.13 0.1  0.9  0.74 0.94 0.45 0.68 0.2  0.63 0.27
 0.61 0.38 0.71 0.85 0.82 0.13 0.05 0.77 0.66]
[ 8  6  3 17 18 21  7 16 10 22 12 14  2  9  0 15 13 11  4 19  5  1 20]
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Amrit varshini 0.94
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Alahiya bilawal 0.9
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Ahir bhairav 0.88
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
Basant 0.85
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
Kafi 0.82
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
Todi 0.77


In [22]:
print(len(y[0]))

23
